spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        ejb:
          interceptor: org.mambey.gestiondestock.interceptor.Interceptor

gimuemoa:
  openapi:
    dev-url: http://localhost:8881
    prod-url: https://gimuemoa-api.com


server:
  port: 8881

flickr:
  apiKey: 45e3d74fde72fa6a0f26be013e27024b
  apiSecret: c1f473f79c1e7b99
  appKey: 72157720884054158-79f70eebab71910d
  appSecret: 53cfc158c56ce6a1

# App Security Properties
edem:
  app:
    jwtHeaderName: Authorization
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000

defaultUserPassword: Zagzagzag

springdoc:
  swagger-ui:
    enabled: true

logging:
  # level:
  #   org:
  #     springframework: DEBUG
  file:
    name: /Users/admin/gestiondestock.log


  
