name: Build and deploy Stock management App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  create-folder:
    name: create folder on ec2 instance
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: sudo mkdir -p /opt/applications/sa

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Téléchargements des sources
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Unit test
      run: mvn -B test --file pom.xml

    - name: Build the application
      run: |
        mvn -B clean
        mvn package --file pom.xml

    - name: Build docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gestiondestock:$(date-'%Y%m%d%H')

    - name: Login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 

    - name: Push to docker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gestiondestock:$(date-'%Y-%m-%d%H-')